before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: Freshly
      name: homebrew-taps
    folder: Formula
    homepage: https://github.com/Freshly/tuber
    description: 🥔
    test: |
      system "#{bin}/tuber -v"
